# Generated by Django 5.1.2 on 2024-12-22 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrating',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
