# Generated by Django 5.1.2 on 2024-12-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
