# Generated by Django 5.1.2 on 2024-12-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
