# Generated by Django 5.1.2 on 2025-01-03 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coupon'),
        ),
    ]
