# Generated by Django 5.1.2 on 2025-01-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_used_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
