# Generated by Django 5.1.2 on 2025-01-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_foodrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
